const mongoose = require("mongoose");

const recommendationStatsSchema = new mongoose.Schema(
    {
        buyer_id: {
            type: String,
            required: true,
            index: true
        },

        merchant_id: {
            type: String,
            required: true,
            index: true
        },

        product_id: {
            type: String,
            required: true,
            index: true
        },

        razorpay_order_id: {
            type: String,
            required: true,
            index: true
        },

        // Recommendation was shown to the buyer
        shown: {
            type: Boolean,
            default: true
        },

        // Buyer added this recommended product to cart
        added_to_cart: {
            type: Boolean,
            default: false
        },

        // Buyer explicitly skipped the recommendation phase
        skipped: {
            type: Boolean,
            default: false
        },

        // Determined by the server using CHECKOUTS
        purchased: {
            type: Boolean,
            default: false
        },

        // Quantity actually purchased
        purchased_quantity: {
            type: Number,
            default: 0
        },

        // Whether the checkout was actually paid + confirmed
        payment_confirmed: {
            type: Boolean,
            default: false
        },

        // Actual value generated by this recommended product calculated from CHECKOUTS
        cross_sell_revenue: {
            type: Number,
            default: 0
        }
    },
    {   
        collection: 'recommendation_stats_collection',
        timestamps: true
    }
);

const RECOMMENDATION_STATS = mongoose.model(
    "recommendation_stats_collection",
    recommendationStatsSchema
);

module.exports = RECOMMENDATION_STATS;